name: My Profile
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  
  #Build's job
  build:
    #needs: tests
    name: Build and Push
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn -ntp -Pprod verify jib:dockerBuild
    - name: Push Docker image
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        script: |
          sudo docker push sample
  deploy:
    needs: build
    name: Pull and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull & Run from Hub
      uses: appleboy/ssh-action@master
      with:
        host: ec2-65-1-109-3.ap-south-1.compute.amazonaws.com
        username: ec2-user
        key: ${{secrets.AWS_PRIVATE_KEY}}
        envs: HITHUB_SHA
        script: |
          sudo docker pull learnwithparth/myprofile
          sudo docker stop mywebsite
          sudo docker rm mywebsite
          sudo docker run --detach --name mywebsite -p 443:443 learnwithparth/myprofile
