name: My Profile
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  deploy:
    #needs: build
    name: Pull and Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Pull & Run from Hub
      uses: appleboy/ssh-action@master
      with:
        host: ec2-65-1-109-3.ap-south-1.compute.amazonaws.com
        username: ec2-user
        key: ${{secrets.AWS_PRIVATE_KEY}}
        envs: HITHUB_SHA
        script: |
          sudo yum install docker -y
          sudo docker pull learnwithparth/sample
          sudo docker stop sample
          sudo docker rm sample
          sudo docker run --detach --name sample -p 8080:8080 learnwithparth/sample
